"""add checklist table

Revision ID: 8c5cc05c3b78
Revises: 52fc0b44deb2
Create Date: 2025-11-05 01:06:30.039468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5cc05c3b78'
down_revision = '52fc0b44deb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_rules')
    with op.batch_alter_table('checklist_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_rule', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.create_table('checklist_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_respected', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
